@startuml
class Dice{
    ..Constructer..
    - Dice()
    - Dice(int min, int max)

    ..Attribut..
    - min :int 
    - max :int
    - value :int

    ..Methoden..
    + roll()
    + getValue()
    + setMinAndMax(int min, int max)
}
@enduml

